### ISSUE TITLE
make failed

### ISSUE THREAD

**Issue by DongZhou12345** [open-webrtc-toolkit/QoSTestFramework#8]
/root/QoSTestFramework-master/QOStestclient/owt.h:6:34: fatal error：owt/base/commontypes.h：No such file or directory
 #include "owt/base/commontypes.h"
                                  ^

make[2]: *** [CMakeFiles/owt_conf_sample.dir/conferencesample.cc.o]error 1
make[1]: *** [CMakeFiles/owt_conf_sample.dir/all] error 2
make: *** [all] error 2

**Comment by JinChengShi** [comment]
This file is the head file of third party, please build https://github.com/open-webrtc-toolkit/owt-client-native and copy the include file.

**Comment by karantelebu** [comment]
https://github.com/open-webrtc-toolkit/owt-client-native/tree/master/talk/owt/sdk/include/cpp/owt

copy this folder to the QOStestclient folder and try. It worked for me

**Comment by yanbin7** [comment]
close the issue. It  works fine now.
